#!/bin/sh

DAEMON=/usr/sbin/ntpd
PIDFILE=/run/ntpd.pid

if [ -r /etc/default/ntp ]; then
        . /etc/default/ntp
fi

if [ -e /run/ntp.conf.dhcp ]; then
        NTPD_OPTS="$NTPD_OPTS -c /run/ntp.conf.dhcp"
fi

NTPD_OPTS="$NTPD_OPTS -u $(getent passwd ntp | cut -f 3,4 -d:)"

exec $DAEMON -p $PIDFILE $NTPD_OPTS

