#!/bin/sh

set -e

if [ -r /etc/default/ntpdate ]; then
	. /etc/default/ntpdate
fi

if [ "$NTPDATE_USE_NTP_CONF" = yes ]; then
	if [ -n /etc/ntp.conf ]; then
		NTPSERVERS=$(sed -rne 's/^(servers?|peer|pool)[[:space:]]+(-[46][[:space:]]+)?([-_.:[:alnum:]]+).*$/\3/p' /etc/ntp.conf | grep -v '^127\.127\.') || [ $? -le 1 ]
	fi
fi

if [ "$IGNORE_DHCP" != "yes" ] && [ -r /run/ntpdate.dhcp ]; then
	. /run/ntpdate.dhcp
fi

# shellcheck disable=SC2086
exec /usr/sbin/ntpdate $NTPOPTIONS "$@" $NTPSERVERS
